version: '3'
services:
  adonis-trial:
    container_name: adonis-trial
    image: node:18
    restart: always
    volumes:
      - .:/app
    working_dir: /app
    port:
      - 8080:3333
    command:
      - node
      - ace
      - serve
      - --watch
